# Dockerfile for local UI development
#
# Copyright 2020 Byte Technology. All rights reserved.

FROM node:12-buster-slim AS builder

RUN apt-get update && apt-get upgrade -y && \
  apt-get install -y iproute2 iputils-ping sudo && \
  apt-get auto-remove && \
  rm -r /var/lib/apt/lists /var/cache/apt/archives

WORKDIR /home/node/micro-{{serviceName}}

COPY . .

RUN npm install

CMD ["npm", "run", "ui"]
